spring:
  application:
    name: lab1As
  datasource:
    # Para desarrollo local usa PostgreSQL local, para producci√≥n usa las variables de Neon
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lab1As}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true

server:
  port: ${PORT:8080}

logging:
  level:
    '[com.udea.lab1As]': INFO
    '[org.springframework]': INFO
    '[org.hibernate.SQL]': DEBUG
